#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2017, Joyent, Inc.
#

. /lib/svc/share/smf_include.sh

smf_is_globalzone || exit $SMF_EXIT_OK

exec /usr/sbin/pcscd --force-reader-polling
