#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2001, 2010, Oracle and/or its affiliates. All rights reserved.
#
# Copyright (c) Joyent Inc

VERS=$1-64

PREFIX=${DESTDIR}/usr
LIBDIR=${PREFIX}/lib/amd64

mkdir -p $LIBDIR

. ../install.subr

cd ${VERS}

_install D libbz2.so.1 ${LIBDIR}/libbz2.so.1 755
_install L libbz2.so.1 ${LIBDIR}/libbz2.so

exit 0
