#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2010 Joyent Inc.
#

PREFIX=${DESTDIR}/usr
ROOTLIBDIR=${DESTDIR}/lib
LIBDIR=${PREFIX}/lib
INCDIR=${PREFIX}/include
SHAREDIR=${PREFIX}/share
MAN3DIR=${SHAREDIR}/man/man3

. ../install.subr
	
cd ${VERS}

mkdir -p ${ROOTLIBDIR} ${LIBDIR} ${INCDIR} ${SHAREDIR} ${MAN3DIR}

_install D libz.so.1.2.3 ${ROOTLIBDIR}/libz.so.1 755
_install L ../../lib/libz.so.1 ${LIBDIR}/libz.so.1
_install L libz.so.1 ${ROOTLIBDIR}/libz.so
_install L libz.so.1 ${LIBDIR}/libz.so

for i in zlib.h zconf.h
do
	_install N ${i} ${INCDIR}/${i} 644
done

exit 0
