#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 2010 Joyent Inc.
# Copyright 2025 MNX Cloud, Inc.
# Copyright 2025 Edgecast Cloud LLC.
#

PREFIX=${DESTDIR}/usr
LIBDIR=${PREFIX}/lib/amd64
INCDIR=${PREFIX}/include

mkdir -p ${LIBDIR} ${INCDIR}

. ../install.subr

cd ${VERS}

_install D lib/.libs/libexpat.so.1.11.2 ${LIBDIR}/libexpat.so.1.11.2 555
_install L libexpat.so.1.11.2 ${LIBDIR}/libexpat.so
_install L libexpat.so.1.11.2 ${LIBDIR}/libexpat.so.1
_install L libexpat.so.1.11.2 ${LIBDIR}/libexpat.so.0

exit 0
