#!/usr/bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

set -o errexit
set -o pipefail

NODE=$1
OUT=$2

if [[ -z ${NODE} || ! -x ${NODE} || -z ${OUT} || -n $3 ]]; then
    echo "Usage: $0 <node> <output>" >&2
    exit 1
fi

VER=$(${NODE} -e 'console.log(process.version)')

cat >${OUT} <<EOF
// This file was autogenerated, do not edit manually.
//
// Copyright (c) 2012 Joyent Inc., All rights reserved.
//

var required_version='${VER}';
var util = require('util');

exports.assert = function () {
    // this allows overriding for development
    if (process.env.DISABLE_NODE_VERSION_CHECK) {
        return;
    }
    if (process.version !== required_version) {
        throw new Error(util.format('You must be running node %s to use this '
            + 'platform library. You are currently using version %s '
            + '("%s %s ...").', required_version, process.version,
            process.execPath, process.argv[1]));
    }
};
EOF

exit 0
