#include <stdio.h>

int
main(int argc, char *argv[])
{
	/* CSTYLED */
	static const char *version_js =
"// This file was autogenerated, do not edit manually.\n"
"//\n"
"// Copyright (c) 2013 Joyent Inc., All rights reserved.\n"
"//\n\n"
"var required_version='%s';\n"
"var util = require('util');\n\n"
"exports.assert = function () {\n"
"\t// this allows overriding for development\n"
"\tif (process.env.DISABLE_NODE_VERSION_CHECK) {\n"
"\t\treturn;\n"
"\t}\n"
"\tif (process.version !== required_version) {\n"
"\t\tthrow new Error(util.format('You must be running node %%s to use this '\n"
"\t\t    + 'platform library. You are currently using version %%s '\n"
"\t\t    + '(\"%%s %%s ...\").', required_version, process.version,\n"
"\t\t    process.execPath, process.argv[1]));\n"
"\t}\n"
"};\n";

	(void) printf(version_js, NODE_VERSION);
	return (0);
}
